version: '2'

services:
  pdi:
    # build: . # Caso queira personalizar o Dockerfile.
    image: gfviegas/pdi # Se usar a opção build, comente esta.
    working_dir: /code/src
    container_name: pdi-container
    volumes:
      - ./:/code
    environment:
      - DISPLAY=${DISPLAY_X}
